version: '3.8'

services:
  # 1. BASE DE DATOS (MongoDB)
  db:
    container_name: api_client_database
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./dockerdata/db:/data/db

  # 2. BACKEND (Node.js + Express)
  backend:
    build: ./backend
    container_name: api_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/fresnofotos
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=cambiame_por_algo_seguro  # Asegúrate de que coincida con tu .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Persistencia de fotos: se guardarán en tu carpeta local backend/uploads
      - ./backend/uploads:/app/uploads
      # Persistencia de assets (marcas de agua, etc.)
      - ./backend/assets:/app/assets

  # 3. FRONTEND (Vite + React)
  frontend:
    build: ./frontend
    container_name: api_client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true